// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kcmvp/iam.go/ent/account"
	"github.com/kcmvp/iam.go/ent/oauth"
	"github.com/kcmvp/iam.go/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescCreateTime is the schema descriptor for create_time field.
	accountDescCreateTime := accountMixinFields0[0].Descriptor()
	// account.DefaultCreateTime holds the default value on creation for the create_time field.
	account.DefaultCreateTime = accountDescCreateTime.Default.(func() time.Time)
	// accountDescUpdateTime is the schema descriptor for update_time field.
	accountDescUpdateTime := accountMixinFields0[1].Descriptor()
	// account.DefaultUpdateTime holds the default value on creation for the update_time field.
	account.DefaultUpdateTime = accountDescUpdateTime.Default.(func() time.Time)
	// account.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	account.UpdateDefaultUpdateTime = accountDescUpdateTime.UpdateDefault.(func() time.Time)
	oauthMixin := schema.OAuth{}.Mixin()
	oauthMixinFields0 := oauthMixin[0].Fields()
	_ = oauthMixinFields0
	oauthFields := schema.OAuth{}.Fields()
	_ = oauthFields
	// oauthDescCreateTime is the schema descriptor for create_time field.
	oauthDescCreateTime := oauthMixinFields0[0].Descriptor()
	// oauth.DefaultCreateTime holds the default value on creation for the create_time field.
	oauth.DefaultCreateTime = oauthDescCreateTime.Default.(func() time.Time)
	// oauthDescUpdateTime is the schema descriptor for update_time field.
	oauthDescUpdateTime := oauthMixinFields0[1].Descriptor()
	// oauth.DefaultUpdateTime holds the default value on creation for the update_time field.
	oauth.DefaultUpdateTime = oauthDescUpdateTime.Default.(func() time.Time)
	// oauth.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	oauth.UpdateDefaultUpdateTime = oauthDescUpdateTime.UpdateDefault.(func() time.Time)
}
