// Code generated by entc, DO NOT EDIT.

package fun

const (
	// Label holds the string label denoting the fun type in the database.
	Label = "fun"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// Table holds the table name of the fun in the database.
	Table = "funs"
	// RoleTable is the table that holds the role relation/edge. The primary key declared below.
	RoleTable = "role_funcs"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
)

// Columns holds all SQL columns for fun fields.
var Columns = []string{
	FieldID,
}

var (
	// RolePrimaryKey and RoleColumn2 are the table columns denoting the
	// primary key for the role relation (M2M).
	RolePrimaryKey = []string{"role_id", "fun_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
